frontend/src/App.js, frontend/src/styles.css
created navbar and redirect links
deleted index.css
=> frontend-hao

frontend/src/App.js, frontend/src/components/Button.css, frontend/src/components/Button.jsx, frontend/src/components/Navbar.jsx
Created a simple button
Added styling similar to the figma
Changed the link of the review in the navbar so that you have to click on the button
Open to other changes
=> Created button with styling

frontend/src/App.js, frontend/src/components/Navbar.jsx, frontend/src/pages/login/Login.jsx
Added basic interface for the login page, allowing users to log in with google via a button that brings up a pop-up where they can sign in. Once a user is logged in, the users are redirected to the home page and a flag is set in local storage that tells the webpage to not display a link to the login page. Instead of the link to login, the home page now displays a log out button, where clicking it will log a user out, clear local storage, and redirect the user to the login page.
=> Basic Login and Logout functionality

frontend/src/App.js, frontend/src/components/Button.css, frontend/src/components/Button.jsx, frontend/src/components/Navbar.jsx, frontend/src/components/Navbar.scss, frontend/src/components/SearchBar.scss, frontend/src/pages/home/Home.scss, frontend/src/styles.css
styled navigation bar to look more like Figma design
=> styled nav bar

frontend/src/pages/login/Login.jsx
Added functionality to the Login page for after logging in, the program checks to see if there is already a user doc associated with that user. It does so by querying the users collection and checking if there's any doc with the same uid as the current user. If not, then the program creates a blank doc with the user's uid, name, and blank fields to eventually hold the user's posted reviews and liked reviews.
=> 21 create user document

frontend/src/components/BathroomRow.jsx, frontend/src/components/BathroomRow.scss
Created a switch statement for the poop cases. Overall rating will be rounded to nearest .5. Styled the poops.
Changed image and alt for the heart class.
Created individual pngs for each possible review.
One thing to note is that I left the code in for an array of 5 single poops if we want to dynamically change them later instead of just having static images.
=> Poops added to Bathroom Row

frontend/src/components/BathroomListings.jsx, frontend/src/components/BathroomRow.jsx, frontend/src/components/BathroomRow.scss, frontend/src/pages/home/Home.jsx, frontend/src/pages/home/Home.scss
Dynamically create bathroom listings from Firebase.
=> 16 display bathroom list

frontend/src/pages/login/Login.jsx, frontend/src/pages/login/Login.scss
styled colors, fonts, button for google login prompt
=> user page styling

frontend/src/App.js, frontend/src/components/Navbar.jsx, frontend/src/components/Navbar.scss, frontend/src/pages/login/Login.jsx, frontend/src/pages/user/User.jsx, frontend/src/pages/user/User.scss
Added user page (not fully implemented yet)
You access user page by clicking on user icon. User stays logged in, but log out button is gone for now. (Make a logout button later)
Added dynamic profile picture and name to user page.
Need to add log out button or way to logout (temporary way to log out is to go back to main page and refresh)
=> Added User Page

frontend/src/pages/bathroom/BathroomPage.jsx, frontend/src/pages/bathroom/BathroomPage.scss
- bug: spacing is a little weird with scores, most likely a better way to do it
=> finish banner styling of dynamic pages

frontend/src/components/BathroomListings.jsx
Created effect to clear topReviewTexts array before pushing updated reviews to it
=> Bugfix: Top review texts broken after filters

frontend/src/components/BathroomListings.jsx, frontend/src/components/SearchBar.jsx, frontend/src/components/SearchBar.scss, frontend/src/pages/home/Home.jsx
Made it so that before mapping through the data and displaying the bathroom rows, do a substring filter based on what is typed in the search box. Also decided to rework the design such that the filter options on the home page include a search bar, and I recommend we remove the search bar in the navbar because it is not relevant to every page.
=> 19 search bar

frontend/src/App.js, frontend/src/pages/home/Home.jsx
Keep authentication after refresh or navigation to separate page
=> Fix auth clear after refresh

frontend/src/components/BathroomRow.scss, frontend/src/components/Navbar.jsx, frontend/src/components/Navbar.scss
fixes visual bug with user profile when logged in
=> refactor navbar organization

frontend/src/pages/bathroom/BathroomPage.scss, frontend/src/pages/bathroom/BathroomPageRow.jsx
- reviews are dynamically listed from firebase in room's page
=> finished dynamic bathroom pages

frontend/src/components/BathroomRow.jsx
Added null check to prevent undefined reading
=> Bugfix: error with 0 favorited bathrooms

frontend/src/components/BathroomRow.scss, frontend/src/pages/add_bathroom/AddBathroom.jsx, frontend/src/pages/add_bathroom/AddBathroom.scss
AddBathroom page now displays based on type of user.
For admins, there is a form to directly create a document in Firebase.
Regular users are not authorized to view the page. This will be changed later with a request form.
=> 48 admin panel to create bathrooms

frontend/src/components/SearchBar.scss
decrease length of searchbar in navbar
=> fix searchbar length

frontend/src/components/BathroomListings.jsx
Map topReviewText directly to bathroomList entry, and use that as prop for BathroomRow
=> Top review text correct after applying search

frontend/src/pages/bathroom/BathroomPage.jsx, frontend/src/pages/bathroom/BathroomPage.scss
- decimal truncated to first decimal place
-  spacing is even
=> truncated decimals in reviewpages, fixed spacing

frontend/src/pages/review/Review.jsx, frontend/src/pages/review/Review.scss, frontend/src/pages/review/StarRating.jsx
same changes as last dynamic star changes in branch 32
=> cleaned up changes (up-to-date with main)

frontend/src/components/BathroomListings.jsx, frontend/src/pages/home/Home.jsx, frontend/src/pages/login/Login.scss, frontend/src/pages/review/CleanRating.jsx, frontend/src/pages/review/Review.jsx, frontend/src/pages/review/Review.scss, frontend/src/pages/review/StarRating.jsx
- stars are now correctly updated to respective categories
- checked whether database values are correct with bathroom review ratings for each category
=> completed linking write-review page to backend 

frontend/src/pages/review/Review.jsx, frontend/src/pages/review/Review.scss
- centered submit button
- shortened background text box
=> review page styling

frontend/src/pages/review/Review.jsx, frontend/src/pages/review/Review.scss
- text box and buttons
- adjusting submit button and text size
praying.
=> write review CENTERING components

frontend/src/components/BathroomRow.scss
Reverts kyley422/bruin-banos#98
=> Revert "changed padding on home page"
